<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TeletextRecoveReese.Core</RootNamespace>
    <AssemblyName>TeletextRecoveReese.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/VbiPatterns/vhs/*.dat" />
  </ItemGroup>

</Project>
